// Research disciplines and lines used by both the standard protocol's
// "Descripción" section and the teacher-thesis protocol's equivalent.

export const DISCIPLINES = [
  'Ciencias Económicas y de la Administración',
  'Ciencias de la Salud',
  'Humanidades, Educación y Ciencias Sociales',
  'Teología',
] as const

export type Discipline = (typeof DISCIPLINES)[number]

export const linesForDiscipline = (v: string): string[] => {
  if (v === 'Ciencias Económicas y de la Administración')
    return [
      'Contabilidad y auditoría: Management y Estudios Organizacionales',
      'Contabilidad y auditoría: Ética y Compliance',
      'Contabilidad y auditoría: Liderazgo',
      'Economía',
      'Emprendimiento y ecosistemas emprendedores',
      'Dinero e inflación en argentina',
      'Robótica e impresión 3D',
      'Ingeniería en Sistemas',
      'Tecnología asistiva',
      'Informática industrial',
      'Educación y cultura financiera',
      'Formación y enseñanza en administración y contabilidades',
      'Efectos y utilización de tecnologias en Ciencias Económica',
    ]
  if (v === 'Ciencias de la Salud')
    return [
      'Promoción de la salud',
      'Restauración de la salud',
      'Educación en ciencias de la salud',
      'Bioética',
    ]
  if (v === 'Humanidades, Educación y Ciencias Sociales')
    return [
      'Psicometría y evaluación psicológica',
      'Neuropsicología',
      'Psicología educacional',
      'Psicología de la familia, Parentalidad',
      'Psicología del desarrollo',
      'Recursos protectores y psicología positiva',
      'Psicología de la salud',
      'Psicología de la religión y la espiritualidad',
      'Terminología, lexicografía y fraseología',
      'Tecnologías aplicadas a la traducción',
      'Teoría de la traducción y la interpretación',
      'Didáctica de la traducción y la interpretación',
      'Estudio cultural de la traducción y la interpretación',
      'Aspectos profesionales y laborales de la traducción y la interpretación',
      'La traducción especializada',
      'Estudios sobre interpretación',
      'Formación de docentes de lenguas extranjeras',
      'Lingüística aplicada a la adquisición del inglés como segunda lengua',
      'Metodología, enseñanza y evaluación de lenguas extranjeras',
      'Uso de las TIC en el aula de lengua extranjera',
      'Estudios de literatura en lengua inglesa',
      'Educación, reeducación y prevención en las actividades físicas',
      'Actividad física como prevención de enfermedades en adultos jóvenes',
      'Educación física en la prevención de adicciones',
      'Influencia de la actividad física en el rendimiento integral',
      'La actividad física y la autoestima',
      'Dirección de comunicación',
      'Producción de medios',
      'Comunicación integrada de marketing',
      'Nuevas tecnologías y entornos digitales',
      'Comunicación audiovisual',
      'Análisis de contenidos en medios',
      'La imagen como recurso de información y comunicación',
      'Sistematización de una filosofía bíblica: supuestos ontológicos, epistemológicos, antropológicos, teológicos y cosmológicos de las Escrituras',
      'Desarrollos actuales de la filosofía y su significado para la comprensión bíblica de la relación entre fe, razón, ciencia y religión',
      'Deconstrucción de los supuestos básicos de la filosofía clásica, moderna y contemporánea desde la filosofía bíblica',
      'La epistemología o filosofía de la ciencia contemporáneas y el descubrimiento de la razón hipotética e interpretativa',
      'Postmodernismo y fe cristiana',
      'Cosmovisión cristiana, ética, política, derecho y sociedad',
      'Humanismo, religiosidad y educación',
      'Estudio de los supuestos filosóficos de la ciencia moderna y su crítica desde los supuestos de la filosofía bíblica',
      'Explicitación de los supuestos ontológicos, epistemológicos y antropológicos de las corrientes de la psicología moderna y su evaluación desde la ontología, la epistemología y la antropología bíblicas',
      'Los nuevos desarrollos de la filosofía en el siglo XXI y su confrontación con la filosofía posmoderna y con la filosofía bíblica',
      'Postmodernidad, hipermodernidad y valores éticos bíblicos',
      "La ciencia del 'ajuste fino' del universo y la tendencia a resucitar científicamente la idea de una inteligencia ordenadora del universo",
    ]
  if (v === 'Teología')
    return [
      'Exégesis veterotestamentaria: Pentateuco',
      'Exégesis veterotestamentaria: Salterio',
      'Exégesis veterotestamentaria: Libros sapienciales',
      'Exégesis veterotestamentaria: Libros proféticos',
      'Filología veterotestamentaria: Análisis semántico',
      'Filología veterotestamentaria: Ecdótica (crítica textual)',
      'Abordajes exegéticos: Evaluación crítica de nuevas metodologías contemporáneas',
      'Abordajes exegéticos: Análisis narrativo o narratología en el AT',
      'Abordajes exegéticos: Estudios sobre intertextualidad',
      'Teología veterotestamentaria: El conflicto cósmico en el AT',
      'Teología veterotestamentaria: Teología bíblica del santuario',
      'Exégesis neotestamentaria: Epístolas paulinas (con especial énfasis en Romanos, Tesalonicenses y Hebreos)',
      'Exégesis neotestamentaria: Escritos joaninos (con especial énfasis en Apocalipsis)',
      'Filología neotestamentaria: Análisis semántico',
      'Filología neotestamentaria: Ecdótica',
      'Abordajes exegéticos: Análisis retórico',
      'Abordajes exegéticos: Análisis epistolográfico',
      'Teología neotestamentaria: El conflicto cósmico en el NT',
      'Teología neotestamentaria: Teología bíblica del santuario',
      'Teología fundamental: El método teológico',
      'Doctrina de Dios: Atributos y acciones divinas',
      'Doctrina de Dios: La Trinidad (unidad y pluralidad de Deidad)',
      'Doctrina de Dios: El lenguaje para hablar de Dios',
      'Doctrina de Dios: Dios y el santuario',
      'Eclesiología: Fundamentos y desafíos de la eclesiología adventista',
      'Eclesiología: Teología de la adoración y la música sacra',
      'Eclesiología: Teología de la predicación',
      'Teología y ética: Aportes del pensamiento teológico a los desafíos éticos contemporáneos',
      'Teología y ética: Ética y religión',
      'Teología y ética: Teología, religión y normativa',
      'Teología y ciencia: Epistemología de la Teología y de la religión',
      'Teología y ciencia: Historia de la ciencia teológica',
      'Teología y ciencia: Ciencia y religión',
      'Teología y filosofía: Pensamiento teológico latinoamericano, autores y corrientes relevantes de pensamiento',
      'Teología y filosofía: Pensamiento posmoderno y teología',
      'Teología y filosofía: Filosofía de la historia',
      'Teología y filosofía: Filosofía de la religión',
      'Teología y filosofía: Presuposiciones filosóficas en la teología',
      'Teología y sociología: Sociología de la religión',
      'Teología, política, derecho y sociedad: Fundamentalismos, fragmentación y movimientos geopolíticos religioso-culturales',
      'Teología, política, derecho y sociedad: Justicia social, derechos humanos e integración teológica en la realidad latinoamericana histórica y contemporánea',
      'Teología, política, derecho y sociedad: Interrelación entre Iglesia y Estado',
      'Teología histórica: Desarrollo de la doctrina del sábado',
      'Teología histórica: Desarrollo de la doctrina de la salvación en el adventismo',
      'Teología histórica: Teología y pensamiento de los padres prenicenos',
      'Historia eclesiástica: Los movimientos reavivalistas norteamericanos como trasfondo del movimiento millerita del siglo XIX',
      'Historia eclesiástica: Protestantismo latinoamericano',
      'Historia del adventismo sudamericano: Antecedentes históricos del adventismo en Sudamérica',
      'Historia del adventismo sudamericano: Personalidades destacadas del adventismo sudamericano',
      'Historia del adventismo sudamericano: Historia de las principales iglesias e instituciones de la IASD en Sudamérica',
      'El don profético y los escritos de Elena G. de White: La doctrina de la inspiración en los escritos de Elena G. de White',
      'El don profético y los escritos de Elena G. de White: Hermenéutica aplicada a los escritos de Elena G. de White',
      'Misiología y Crecimiento de iglesia: Teología de la misión',
      'Misiología y Crecimiento de iglesia: El crecimiento de la IASD en Argentina y Sudamérica',
      'Misiología y Crecimiento de iglesia: Estrategias de crecimiento de iglesia en el contexto latinoamericano',
      'Misiología y Crecimiento de iglesia: Misión urbana',
      'Misiología y Crecimiento de iglesia: Estrategias para plantar iglesias',
      'Misiología y Crecimiento de iglesia: Discipulado cristiano',
      'Misiología y Crecimiento de iglesia: Estrategias y métodos de evangelismo',
      'Misiología y Crecimiento de iglesia: Capacitación de laicos para el servicio misionero',
      'Teología y adoración: Teología de la adoración',
      'Teología y adoración: Teología y ministerio de la adoración',
      'Teología y adoración: Práctica de la música y adoración',
      'Teología y salud: Religiosidad y salud',
      'Teología y salud: Duelo',
      'Teología y salud: Esperanza y salud',
      'Teología y salud: Atención espiritual de pacientes terminales',
      'Teología y salud: Estilo de vida saludable',
      'Liderazgo pastoral: Fundamento bíblico teológico del liderazgo pastoral',
      'Liderazgo pastoral: Liderazgo de organizaciones eclesiásticas',
      'Liderazgo pastoral: Liderazgo espiritual',
      'Liderazgo pastoral: Modelos y estilos de liderazgo (Liderazgo servidor)',
      'Liderazgo pastoral: Los dones espirituales y el liderazgo',
      'Liderazgo pastoral: Administración de conflictos',
      'Liderazgo pastoral: Características del líder cristiano',
      'Liderazgo pastoral: Planificación estratégica',
      'Liderazgo pastoral: Misión y ministerios de la iglesia',
      'Hogar y familia: Educación religiosa de los hijos',
      'Hogar y familia: Relaciones afectivas',
      'Hogar y familia: Sistemas familiares',
      'Teología y educación: Incidencia de las corrientes teológicas contemporáneas en la conformación de la pedagogía actual',
      'Teología y educación: Evaluación crítica de las teorías pedagógicas contemporáneas en el marco de la cosmovisión cristiana',
      'Teología y educación: La transmisión de valores en los ámbitos de la educación teológica',
      'Teología y educación: Fundamentación teológica de la organización curricular y didáctica de la formación religiosa en los distintos niveles educacionales',
      'Teología y educación: Los fundamentos teológicos en relación con la educación popular',
      'Nuevas generaciones: Evangelismo para nuevas generaciones en entornos digitales',
      'Nuevas generaciones: Biblia, cultura y nuevas generaciones',
      'Nuevas generaciones: Narrativa bíblica y comunicación transmedia para nuevas generaciones',
      'Nuevas generaciones: Formación religiosa y transmisión de la fe en adolescentes',
    ]
  return []
}
